### ISSUE TITLE
영화 리뷰 평가 돌려보는 중 오류발생

### ISSUE THREAD

**Issue by kjh-0523** [kwarkmc/EmotionApp#7]
**요약**
메모리 부족

**소개**
아래의 단계에 따라 버그를 설명
1.'2. kimjiho/classifying_movie_review.ipynb'
2. classifying_movie_review.ipynb
3. In[52] line[16]

**설명**
검색 결과 메모리 부족인듯 합니다. CPU로만 돌리면 발생한다는데 GPU까지 돌려 보려고 cuda로 가상 환경 만들어서 실행해봤는데 안됐고요. 시스템의 고급설정 들어가서 메모리 할당도 늘려 봤는데도 안되네요. 
배치사이즈를 줄여보래서 64까진 줄여봤는데 안되고요. 혹시 몰라 1024까지 늘려봐도 안됩니다.
IN[37] line[1]에서 샘플 수를 10000에서 7500,5000까지 줄여봤는데 5000에서는 동작하긴 합니다. 근데 성능이 떨어지진 않을지 걱정되네요 (샘플 수는 자주나오는 단어 수라고 합니다.)

**스크린샷**
![image](https://user-images.githubusercontent.com/124140035/217435292-aa897da8-936d-45f3-9ada-16a9f03b2eb6.png)

**Comment by kwarkmc** [comment]
model.fit 부분에 batch사이즈를 점점 줄이면서 시도해보면 어떨까요

예전에 CNN 학습 돌리다가 메모리 터져서 batch 사이즈를 2로 놓고 하루종일 돌렸었습니당

**Comment by kwarkmc** [comment]
노트북이 12Gb 메모리였는데도 금방 터져서 64보다 더 줄여봐야할듯
